version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Point to the correct folder
    container_name: task-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/taskdb
    command: ["npm", "start"]

  mongo:
    image: mongo:latest
    container_name: task-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
